//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string Control_High {
            get {
                return ResourceManager.GetString("Control_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Control_Low {
            get {
                return ResourceManager.GetString("Control_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file doesn&apos;t exist..
        /// </summary>
        internal static string DeviceInfoForm_ConfigFileDoesntExist {
            get {
                return ResourceManager.GetString("DeviceInfoForm_ConfigFileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string DeviceInfoForm_ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("DeviceInfoForm_ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string DeviceInfoForm_ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("DeviceInfoForm_ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string DeviceInfoForm_Group_Connected {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Group_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk information.
        /// </summary>
        internal static string DeviceInfoForm_Group_DiskInformation {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Group_DiskInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string DeviceInfoForm_Group_Other {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Group_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobo.
        /// </summary>
        internal static string DeviceInfoForm_Label_Directory_Kobo {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Label_Directory_Kobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation SW.
        /// </summary>
        internal static string DeviceInfoForm_Label_Directory_NavigationSW {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Label_Directory_NavigationSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection status.
        /// </summary>
        internal static string DeviceInfoForm_Label_IsConnected {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Label_IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation SW.
        /// </summary>
        internal static string DeviceInfoForm_Label_NavigationSW {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Label_NavigationSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script path.
        /// </summary>
        internal static string DeviceInfoForm_Label_ScriptPath {
            get {
                return ResourceManager.GetString("DeviceInfoForm_Label_ScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device info..
        /// </summary>
        internal static string DeviceInfoForm_NoDeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfoForm_NoDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error..
        /// </summary>
        internal static string DeviceInfoForm_NoError {
            get {
                return ResourceManager.GetString("DeviceInfoForm_NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\nScript was generated and copied to clipboard..
        /// </summary>
        internal static string Generate_ScriptGenerated {
            get {
                return ResourceManager.GetString("Generate_ScriptGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error with parsing file. Check logs..
        /// </summary>
        internal static string Import_Error {
            get {
                return ResourceManager.GetString("Import_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_small {
            get {
                object obj = ResourceManager.GetObject("logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export script.
        /// </summary>
        internal static string Menu_File_Export_Title {
            get {
                return ResourceManager.GetString("Menu_File_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Generate script.
        /// </summary>
        internal static string Menu_File_Generate_Title {
            get {
                return ResourceManager.GetString("Menu_File_Generate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import script.
        /// </summary>
        internal static string Menu_File_Import_Title {
            get {
                return ResourceManager.GetString("Menu_File_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Menu_File_Quit_Title {
            get {
                return ResourceManager.GetString("Menu_File_Quit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string Menu_File_Title {
            get {
                return ResourceManager.GetString("Menu_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string Menu_Help_About_Title {
            get {
                return ResourceManager.GetString("Menu_Help_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string Menu_Help_Title {
            get {
                return ResourceManager.GetString("Menu_Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Czech.
        /// </summary>
        internal static string Menu_Languages_Czech_Title {
            get {
                return ResourceManager.GetString("Menu_Languages_Czech_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;English.
        /// </summary>
        internal static string Menu_Languages_English_Title {
            get {
                return ResourceManager.GetString("Menu_Languages_English_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Languages.
        /// </summary>
        internal static string Menu_Languages_Title {
            get {
                return ResourceManager.GetString("Menu_Languages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh device.
        /// </summary>
        internal static string Menu_Tool_RefreshDevice_Title {
            get {
                return ResourceManager.GetString("Menu_Tool_RefreshDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Tool_Setting_Title {
            get {
                return ResourceManager.GetString("Menu_Tool_Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Menu_Tool_Title {
            get {
                return ResourceManager.GetString("Menu_Tool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Menu_Unity_Device_Title {
            get {
                return ResourceManager.GetString("Menu_Unity_Device_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read config.
        /// </summary>
        internal static string Menu_Unity_ReadConfig_Title {
            get {
                return ResourceManager.GetString("Menu_Unity_ReadConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        internal static string Menu_Unity_Title {
            get {
                return ResourceManager.GetString("Menu_Unity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write config.
        /// </summary>
        internal static string Menu_Unity_WriteConfig_Title {
            get {
                return ResourceManager.GetString("Menu_Unity_WriteConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart application to apply settings..
        /// </summary>
        internal static string MessageBox_PleaseRestartApplication {
            get {
                return ResourceManager.GetString("MessageBox_PleaseRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic linear compensation is implemented by y =A*x+B equation. This value is A coefficient..
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationAParam_Description {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationAParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param A.
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationAParam_Title {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationAParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationAParam_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationAParam_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic linear compensation is implemented by y =A*x+B equation. This value is B coefficient..
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationBParam_Description {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationBParam_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param B.
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationBParam_Title {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationBParam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_AirspeedCompensationBParam_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_AirspeedCompensationBParam_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base sound frequency - higher values means higher pitch. The oscilation frequency value for highest volume is around 2800..
        /// </summary>
        internal static string PROPERTY_BaseFrequency_Description {
            get {
                return ResourceManager.GetString("PROPERTY_BaseFrequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Frequency.
        /// </summary>
        internal static string PROPERTY_BaseFrequency_Title {
            get {
                return ResourceManager.GetString("PROPERTY_BaseFrequency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_BaseFrequency_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_BaseFrequency_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario beep speed. For slower sound use lower values. For quick beeps use higher values..
        /// </summary>
        internal static string PROPERTY_BeepRateMultiplier_Description {
            get {
                return ResourceManager.GetString("PROPERTY_BeepRateMultiplier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep Rate Multiplier.
        /// </summary>
        internal static string PROPERTY_BeepRateMultiplier_Title {
            get {
                return ResourceManager.GetString("PROPERTY_BeepRateMultiplier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_BeepRateMultiplier_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_BeepRateMultiplier_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airspeed Compensation.
        /// </summary>
        internal static string PROPERTY_GROUP_AirspeedCompensation {
            get {
                return ResourceManager.GetString("PROPERTY_GROUP_AirspeedCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string PROPERTY_GROUP_Sounds {
            get {
                return ResourceManager.GetString("PROPERTY_GROUP_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string PROPERTY_GROUP_Sounds_Basic {
            get {
                return ResourceManager.GetString("PROPERTY_GROUP_Sounds_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Sound.
        /// </summary>
        internal static string PROPERTY_GROUP_Sounds_LowSound {
            get {
                return ResourceManager.GetString("PROPERTY_GROUP_Sounds_LowSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario.
        /// </summary>
        internal static string PROPERTY_GROUP_Vario {
            get {
                return ResourceManager.GetString("PROPERTY_GROUP_Vario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario sound treshold for lift signalisation..
        /// </summary>
        internal static string PROPERTY_LiftTreshold_Description {
            get {
                return ResourceManager.GetString("PROPERTY_LiftTreshold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Threshold.
        /// </summary>
        internal static string PROPERTY_LiftTreshold_Title {
            get {
                return ResourceManager.GetString("PROPERTY_LiftTreshold_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_LiftTreshold_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_LiftTreshold_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low volume mode sound frequency - higher values means higher pitch..
        /// </summary>
        internal static string PROPERTY_LowSoundBaseFrequency_Description {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundBaseFrequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Frequency.
        /// </summary>
        internal static string PROPERTY_LowSoundBaseFrequency_Title {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundBaseFrequency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_LowSoundBaseFrequency_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundBaseFrequency_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario sound level in low volume mode..
        /// </summary>
        internal static string PROPERTY_LowSoundVolume_Description {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundVolume_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string PROPERTY_LowSoundVolume_Title {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundVolume_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_LowSoundVolume_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_LowSoundVolume_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_Sensitivity__ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_Sensitivity__ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario sensitivity. Higher value means higher sensitivity. You can tune this so the vario reactions suits you the best..
        /// </summary>
        internal static string PROPERTY_Sensitivity_Description {
            get {
                return ResourceManager.GetString("PROPERTY_Sensitivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        internal static string PROPERTY_Sensitivity_Title {
            get {
                return ResourceManager.GetString("PROPERTY_Sensitivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vario sound treshold for sink signalisation.
        /// </summary>
        internal static string PROPERTY_SinkTreshold_Description {
            get {
                return ResourceManager.GetString("PROPERTY_SinkTreshold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sink Threshold.
        /// </summary>
        internal static string PROPERTY_SinkTreshold_Title {
            get {
                return ResourceManager.GetString("PROPERTY_SinkTreshold_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PROPERTY_SinkTreshold_ValidationMessage {
            get {
                return ResourceManager.GetString("PROPERTY_SinkTreshold_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Setting_Property_Language {
            get {
                return ResourceManager.GetString("Setting_Property_Language", resourceCulture);
            }
        }
    }
}
